[metadata]
name = odoo14-addon-gelato-connector
version = attr: odoo.addons.gelato_connector.__manifest__.__version__
author = Contributors
author_email =
description = Gelato Print-on-Demand Connector for Odoo
long_description = file: README.rst
long_description_content_type = text/x-rst
url = https://github.com/Najah69/odoo-gelato-connector
project_urls =
    Source = https://github.com/Najah69/odoo-gelato-connector
classifiers =
    Programming Language :: Python
    Framework :: Odoo
    Framework :: Odoo :: 18.0

[options]
packages = find:
include_package_data = True
zip_safe = False
install_requires =
    requests

[options.extras_require]
test =
    pytest-odoo
